=== s0tiria/Document-structuring/exercices/exercice3a.dtd
<!ELEMENT tomes ((tome))>
<!ELEMENT tome EMPTY>
<!ATTLIST tome
	nb_pages CDATA #REQUIRED
>
<!ELEMENT titre EMPTY>
<!ELEMENT num EMPTY>
<!ELEMENT nb_pages EMPTY>
<!ELEMENT livres ((livre))>
<!ELEMENT livre ((titre, auteurs, tomes, edition))>
<!ELEMENT lieuImpression EMPTY>
<!ELEMENT lieuEdition EMPTY>
<!ELEMENT journal ((nb_pages, num, avis))>
<!ATTLIST journal
	anneePub CDATA #REQUIRED
	nom CDATA #REQUIRED
>
<!ELEMENT edition ((editeur, lieuEdition, lieuImpression, ISBN))>
<!ELEMENT editeur EMPTY>
<!ELEMENT bibliographie ((livres, articles))>
<!ELEMENT avis EMPTY>
<!ELEMENT auteurs ((auteur+))>
<!ELEMENT auteur EMPTY>
<!ELEMENT articles ((article))>
<!ELEMENT article ((titre, auteurs, journal))>
<!ELEMENT ISBN EMPTY>

=== s0tiria/Document-structuring/exercices/exercice3a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliographie SYSTEM "exercice3a.dtd">
<bibliographie>
	<livres>
		<livre>
			<titre/>
			<auteurs>
				<auteur/>
				<auteur/>
			</auteurs>
			<tomes>
				<tome nb_pages=""/>
			</tomes>
			<edition>
				<editeur/>
				<lieuEdition/>
				<lieuImpression/>
				<ISBN/>
			</edition>
		</livre>
	</livres>
	<articles>
		<article>
			<titre/>
			<auteurs>
				<auteur/>
			</auteurs>
			<journal nom="" anneePub="">
				<nb_pages/>
				<num/>
				<avis/>
			</journal>
		</article>
	</articles>
</bibliographie>
