=== s0tiria/Document-structuring/exercices/exercice11.dtd
<!ELEMENT phraseFR (#PCDATA)>
<!ELEMENT phraseEN (#PCDATA)>
<!ELEMENT pair ((phraseEN, phraseFR, annot1, annot2))>
<!ATTLIST pair
	id (3599 | 3598 | 3597 | 3596 | 3595 | 3594 | 3593 | 3592 | 3591 | 3590 | 3589 | 3588 | 3587 | 3586 | 3585 | 3584 | 3583 | 3582 | 3581 | 3580 | 3579 | 3578 | 3577 | 3576 | 3575 | 3574 | 3573 | 3572 | 3571 | 3570 | 3569 | 3568 | 3567 | 3566 | 3565 | 3564 | 3563 | 3562 | 3561 | 3560 | 3559 | 3558 | 3557 | 3556 | 3555 | 3554 | 3553 | 3552 | 3551 | 3550 | 3549 | 3548 | 3547 | 3546 | 3545 | 3544 | 3543 | 3542 | 3541 | 3540 | 3539 | 3538 | 3537 | 3536 | 3535 | 3534 | 3533 | 3532 | 3531 | 3530 | 3529 | 3528 | 3527 | 3526 | 3525 | 3524 | 3523 | 3522 | 3521 | 3520 | 3519 | 3518 | 3517 | 3516 | 3515 | 3514 | 3513 | 3512 | 3511 | 3510 | 3509 | 3508 | 3507 | 3506 | 3505 | 3504 | 3503 | 3502 | 3501 | 3500 | 3499 | 3498 | 3497 | 3496 | 3495 | 3494 | 3493 | 3492 | 3491 | 3490 | 3489 | 3488 | 3487 | 3486 | 3485 | 3484 | 3483 | 3482 | 3481 | 3480 | 3479 | 3478 | 3477 | 3476 | 3475 | 3474 | 3473 | 3472 | 3471 | 3470 | 3469 | 3468 | 3467 | 3466 | 3465 | 3464 | 3463 | 3462 | 3461 | 3460 | 3459 | 3458 | 3457 | 3456 | 3455 | 3454 | 3453 | 3452 | 3451 | 3450 | 3449 | 3448 | 3447 | 3446 | 3445 | 3444 | 3443 | 3442 | 3441 | 3440 | 3439 | 3438 | 3437 | 3436 | 3435 | 3434 | 3433 | 3432 | 3431 | 3430 | 3429 | 3428 | 3427 | 3426 | 3425 | 3424 | 3423 | 3422 | 3421 | 3420 | 3419 | 3418 | 3417 | 3416 | 3415 | 3414 | 3413 | 3412 | 3411 | 3410 | 3409 | 3408 | 3407 | 3406 | 3405 | 3404 | 3403 | 3402 | 3401 | 3400 | 3399 | 3398 | 3397 | 3396 | 3395 | 3394 | 3393 | 3392 | 3391 | 3390 | 3389 | 3388 | 3387 | 3386 | 3385 | 3384 | 3383 | 3382 | 3381 | 3380 | 3379 | 3378 | 3377 | 3376 | 3375 | 3374 | 3373 | 3372 | 3371 | 3370 | 3369 | 3368 | 3367 | 3366 | 3365 | 3364 | 3363 | 3362 | 3361 | 3360 | 3359 | 3358 | 3357 | 3356 | 3355 | 3354 | 3353 | 3352 | 3351 | 3350 | 3349 | 3348 | 3347 | 3346 | 3345 | 3344 | 3343 | 3342 | 3341 | 3340 | 3339 | 3338 | 3337 | 3336 | 3335 | 3334 | 3333 | 3332 | 3331 | 3330 | 3329 | 3328 | 3327 | 3326 | 3325 | 3324 | 3323 | 3322 | 3321 | 3320 | 3319 | 3318 | 3317 | 3316 | 3315 | 3314 | 3313 | 3312 | 3311 | 3310 | 3309 | 3308 | 3307 | 3306 | 3305 | 3304 | 3303 | 3302 | 3301 | 3300 | 3299 | 3298 | 3297 | 3296 | 3295 | 3294 | 3293 | 3292 | 3291 | 3290 | 3289 | 3288 | 3287 | 3286 | 3285 | 3284 | 3283 | 3282 | 3281 | 3280 | 3279 | 3278 | 3277 | 3276 | 3275 | 3274 | 3273 | 3272 | 3271 | 3270 | 3269 | 3268 | 3267 | 3266 | 3265 | 3264 | 3263 | 3262 | 3261 | 3260 | 3259 | 3258 | 3257 | 3256 | 3255 | 3254 | 3253 | 3252 | 3251 | 3250 | 3249 | 3248 | 3247 | 3246 | 3245 | 3244 | 3243 | 3242 | 3241 | 3240 | 3239 | 3238 | 3237 | 3236 | 3235 | 3234 | 3233 | 3232 | 3231 | 3230 | 3229 | 3228 | 3227 | 3226 | 3225 | 3224 | 3223 | 3222 | 3221 | 3220 | 3219 | 3218 | 3217 | 3216 | 3215 | 3214 | 3213 | 3212 | 3211 | 3210 | 3209 | 3208 | 3207 | 3206 | 3205 | 3204 | 3203 | 3202 | 3201 | 3200 | 3199 | 3198 | 3197 | 3196 | 3195 | 3194 | 3193 | 3192 | 3191 | 3190 | 3189 | 3188 | 3187 | 3186 | 3185 | 3184 | 3183 | 3182 | 3181 | 3180 | 3179 | 3178 | 3177 | 3176 | 3175 | 3174 | 3173 | 3172 | 3171 | 3170 | 3169 | 3168 | 3167 | 3166 | 3165 | 3164 | 3163 | 3162 | 3161 | 3160 | 3159 | 3158 | 3157 | 3156 | 3155 | 3154 | 3153 | 3152 | 3151 | 3150 | 3149 | 3148 | 3147 | 3146 | 3145 | 3144 | 3143 | 3142 | 3141 | 3140 | 3139 | 3138 | 3137 | 3136 | 3135 | 3134 | 3133 | 3132 | 3131 | 3130 | 3129 | 3128 | 3127 | 3126 | 3125 | 3124 | 3123 | 3122 | 3121 | 3120 | 3119 | 3118 | 3117 | 3116 | 3115 | 3114 | 3113 | 3112 | 3111 | 3110 | 3109 | 3108 | 3107 | 3106 | 3105 | 3104 | 3103 | 3102 | 3101 | 3100 | 3099 | 3098 | 3097 | 3096 | 3095 | 3094 | 3093 | 3092 | 3091 | 3090 | 3089 | 3088 | 3087 | 3086 | 3085 | 3084 | 3083 | 3082 | 3081 | 3080 | 3079 | 3078 | 3077 | 3076 | 3075 | 3074 | 3073 | 3072 | 3071 | 3070 | 3069 | 3068 | 3067 | 3066 | 3065 | 3064 | 3063 | 3062 | 3061 | 3060 | 3059 | 3058 | 3057 | 3056 | 3055 | 3054 | 3053 | 3052 | 3051 | 3050 | 3049 | 3048 | 3047 | 3046 | 3045 | 3044 | 3043 | 3042 | 3041 | 3040 | 3039 | 3038 | 3037 | 3036 | 3035 | 3034 | 3033 | 3032 | 3031 | 3030 | 3029 | 3028 | 3027 | 3026 | 3025 | 3024 | 3023 | 3022 | 3021 | 3020 | 3019 | 3018 | 3017 | 3016 | 3015 | 3014 | 3013 | 3012 | 3011 | 3010 | 3009 | 3008 | 3007 | 3006 | 3005 | 3004 | 3003 | 3002 | 3001 | 3000) #REQUIRED
>
<!ELEMENT annot2 (#PCDATA)>
<!ELEMENT annot1 (#PCDATA)>
<!ELEMENT CorpusAnnote ((pair+))>

=== s0tiria/Document-structuring/exercices/exercice11c-resultat.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE CorpusAnnote SYSTEM "exercice11.dtd">

<?xml-stylesheet type="application/xml" href="exercice11c.xsl"?>

<CorpusAnnote>
	<pair id="3000">
		<phraseEN>your honour , i move to disqualify miss vito as a expert witness .</phraseEN>
		<phraseFR>je récuse sa compétence d' experte .</phraseFR>
		<annot1>First annotation: partial; untranslated source word indices: 0 1 2; untranslated target word indices: </annot1>
		<annot2>Second annotation: partial; untranslated source word indices: 0 1 2; untranslated target word indices: </annot2>
	</pair>
	<pair id="3001">
		<phraseEN>i was n't thinking clearly .</phraseEN>
		<phraseFR>mon esprit n' était pas clair .</phraseFR>
		<annot1>First annotation: unperfect</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3002">
		<phraseEN>i calculated his body weight .</phraseEN>
		<phraseFR>j' ai calculé sa masse corporelle .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3003">
		<phraseEN>- i 'm really touched .</phraseEN>
		<phraseFR>- je suis touché . - il y a de quoi .</phraseFR>
		<annot1>First annotation: partial; untranslated source word indices: ; untranslated target word indices: 6 7 8 9 10</annot1>
		<annot2>Second annotation: partial; untranslated source word indices: ; untranslated target word indices: 5 6 7 8 9 10 11</annot2>
	</pair>
	<pair id="3004">
		<phraseEN>you say it wearies you .</phraseEN>
		<phraseFR>vous dites qu' elle vous fatigue aussi .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3005">
		<phraseEN>lead us not into temptation , but deliver us from evil .</phraseEN>
		<phraseFR>" libère nous de la tentation , " " et délivre nous du mal . "</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3006">
		<phraseEN>- somebody rebuilt it .</phraseEN>
		<phraseFR>- quelqu'un l' a reconstruit .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3007">
		<phraseEN>- no , i fucking wo n't keep my voice down !</phraseEN>
		<phraseFR>- je crierai si j' en ai envie !</phraseFR>
		<annot1>First annotation: unperfect</annot1>
		<annot2>Second annotation: unperfect</annot2>
	</pair>
	<pair id="3008">
		<phraseEN>repeat : lower your altitude to 20,000 ft.</phraseEN>
		<phraseFR>je répète : descendez à 7000 m.</phraseFR>
		<annot1>First annotation: partial; untranslated source word indices: 3 4; untranslated target word indices: </annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3009">
		<phraseEN>loretta , i 'm already expelled .</phraseEN>
		<phraseFR>loretta , vous m' avez déjà expulsé .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3010">
		<phraseEN>we got the killer 's god damn dna ?</phraseEN>
		<phraseFR>on a l' adn du tueur ?</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3011">
		<phraseEN>- may we stay this happy forever .</phraseEN>
		<phraseFR>- puisse ce bonheur être éternel .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3012">
		<phraseEN>you can go ahead and try and engage him .</phraseEN>
		<phraseFR>allez -y , essayez de le viser .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3013">
		<phraseEN>i would do as he asks .</phraseEN>
		<phraseFR>vous feriez bien de l' écouter .</phraseFR>
		<annot1>First annotation: unperfect</annot1>
		<annot2>Second annotation: unperfect</annot2>
	</pair>
	<pair id="3014">
		<phraseEN>and i saw the top-secret file to prove it .</phraseEN>
		<phraseFR>j' ai vu le dossier ultrasecret qui le prouve .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3015">
		<phraseEN>you have to get your people out .</phraseEN>
		<phraseFR>il faut faire évacuer .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3016">
		<phraseEN>- whipped cream or berry ?</phraseEN>
		<phraseFR>- crème fouettée ou petits fruits ?</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3017">
		<phraseEN>just keep walkin ' , keep walkin ' .</phraseEN>
		<phraseFR>avance . et voilà .</phraseFR>
		<annot1>First annotation: unperfect</annot1>
		<annot2>Second annotation: unperfect</annot2>
	</pair>
	<pair id="3018">
		<phraseEN>how much do you know about electricity ?</phraseEN>
		<phraseFR>tu t' y connais en électricité ?</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3019">
		<phraseEN>hamburgers , where are you ? .</phraseEN>
		<phraseFR>hamburgers ; où êtes vous ?</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3020">
		<phraseEN>and that 's the way i live</phraseEN>
		<phraseFR>et je vis comme ça</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3021">
		<phraseEN>she 's down to fuck , man .</phraseEN>
		<phraseFR>prête à baiser , mec .</phraseFR>
		<annot1>First annotation: partial; untranslated source word indices: 0 1; untranslated target word indices: </annot1>
		<annot2>Second annotation: unperfect</annot2>
	</pair>
	<pair id="3022">
		<phraseEN>- how can i hold the presents ?</phraseEN>
		<phraseFR>- à la main ?</phraseFR>
		<annot1>First annotation: not corresponding</annot1>
		<annot2>Second annotation: not corresponding</annot2>
	</pair>
	<pair id="3023">
		<phraseEN>i 'm just saying , you know , fabula is a lot less possessive than she used to be .</phraseEN>
		<phraseFR>fabula est beaucoup moins possessive qu' avant .</phraseFR>
		<annot1>First annotation: partial; untranslated source word indices: 0 1 2 3 4 5 6; untranslated target word indices: </annot1>
		<annot2>Second annotation: partial; untranslated source word indices: 0 1 2 3 4 5 6; untranslated target word indices: </annot2>
	</pair>
	<pair id="3024">
		<phraseEN>ok , you 're right .</phraseEN>
		<phraseFR>ok , vous avez raison .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3025">
		<phraseEN>now , could aaron stampler have been present during the murder of archbishop rushman ...</phraseEN>
		<phraseFR>aaron stampler pouvait -il être présent au moment du meurtre</phraseFR>
		<annot1>First annotation: partial; untranslated source word indices: 0 1 11 12 13 14; untranslated target word indices: </annot1>
		<annot2>Second annotation: partial; untranslated source word indices: 0 1 11 12 13 14; untranslated target word indices: </annot2>
	</pair>
	<pair id="3026">
		<phraseEN>three minutes , i can have power back on in the entire park .</phraseEN>
		<phraseFR>j' aurai rétabli le courant dans trois minutes .</phraseFR>
		<annot1>First annotation: partial; untranslated source word indices: 9 10 11 12; untranslated target word indices: </annot1>
		<annot2>Second annotation: partial; untranslated source word indices: 9 10 11 12; untranslated target word indices: </annot2>
	</pair>
	<pair id="3027">
		<phraseEN>he could 've shot your damn head off !</phraseEN>
		<phraseFR>il aurait pu t' arracher toute la tête !</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3028">
		<phraseEN>that depends , gentlemen .</phraseEN>
		<phraseFR>ça dépend , messieurs .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3029">
		<phraseEN>miami . you do whatever work comes your way .</phraseEN>
		<phraseFR>vous faites n' importe quel job qui se présente .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3030">
		<phraseEN>that 's the way a clock works .</phraseEN>
		<phraseFR>pourquoi " joli " ?</phraseFR>
		<annot1>First annotation: not corresponding</annot1>
		<annot2>Second annotation: not corresponding</annot2>
	</pair>
	<pair id="3031">
		<phraseEN>we had a pretty tough season , so naturally , the show went into the red .</phraseEN>
		<phraseFR>on a eu une saison assez dure , alors , le spectacle était dans le rouge .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3032">
		<phraseEN>brad and i are watching the house .</phraseEN>
		<phraseFR>brad et moi gardons la maison .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3033">
		<phraseEN>how many buildings in town is that ?</phraseEN>
		<phraseFR>ça fait combien de bâtiments ça ?</phraseFR>
		<annot1>First annotation: partial; untranslated source word indices: 3 4; untranslated target word indices: </annot1>
		<annot2>Second annotation: partial; untranslated source word indices: 3 4; untranslated target word indices: </annot2>
	</pair>
	<pair id="3034">
		<phraseEN>uh , no. . . party sounds awesome , dude .</phraseEN>
		<phraseFR>la fête a l' air génial .</phraseFR>
		<annot1>First annotation: sure</annot1>
		<annot2>Second annotation: sure</annot2>
	</pair>
	<pair id="3035">
		<phraseEN>if that 's the way it was , can you ever forgive me ?</phraseEN>
