=== s0tiria/Document-structuring/exercices/exercice1.dtd
<!ELEMENT volume (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT source ((ville, dép))>
<!ELEMENT pH (#PCDATA)>
<!ELEMENT nitrates (#PCDATA)>
<!ELEMENT magnésium (#PCDATA)>
<!ELEMENT ions_pos ((calcium, magnésium))>
<!ELEMENT ions_nég ((chlorures, nitrates))>
<!ELEMENT dép (#PCDATA)>
<!ELEMENT contenu_par_litre ((ions_pos, ions_nég, autres))>
<!ELEMENT code_barre (#PCDATA)>
<!ELEMENT chlorures (#PCDATA)>
<!ELEMENT calcium (#PCDATA)>
<!ELEMENT autres (#PCDATA)>
<!ELEMENT Bouteille ((volume, code_barre, pH, source, contenu_par_litre))>
<!ATTLIST Bouteille
	marque (Volvic | Cristaline) #REQUIRED
>
<!ELEMENT BOUTEILLES ((Bouteille+))>

=== s0tiria/Document-structuring/exercices/exercice1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BOUTEILLES SYSTEM "exercice1.dtd">
<BOUTEILLES>
	<Bouteille marque="Cristaline">
		<volume>150 cl</volume>
		<code_barre>3274080005003</code_barre>
		<pH>7,45</pH>
		<source>
			<ville>St-Cyr</ville>
			<dép>Loiret</dép>
		</source>
		<contenu_par_litre>
			<ions_pos>
				<calcium>71 mg</calcium>
				<magnésium>5,5 mg</magnésium>
			</ions_pos>
			<ions_nég>
				<chlorures>20 mg</chlorures>
				<nitrates>1 mg</nitrates>
			</ions_nég>
			<autres>fer</autres>
		</contenu_par_litre>
	</Bouteille>
	<Bouteille marque="Cristaline">
		<volume>50 cl</volume>
		<code_barre>3268840001008</code_barre>
		<pH>7,4</pH>
		<source>
			<ville>Aurèle</ville>
			<dép>les Alpes Maritimes</dép>
		</source>
		<contenu_par_litre>
			<ions_pos>
				<calcium>98 mg</calcium>
				<magnésium>4 mg</magnésium>
			</ions_pos>
			<ions_nég>
				<chlorures>3,6 mg</chlorures>
				<nitrates>2 mg</nitrates>
			</ions_nég>
			<autres>-</autres>
		</contenu_par_litre>
	</Bouteille>
	<Bouteille marque="Volvic">
		<volume>50 cl</volume>
		<code_barre>3057640117008</code_barre>
		<pH>7</pH>
		<source>
			<ville>Volvic</ville>
			<dép>Puy-de-Dôme</dép>
		</source>
		<contenu_par_litre>
			<ions_pos>
				<calcium>11,5 mg</calcium>
				<magnésium>8,0 mg</magnésium>
			</ions_pos>
			<ions_nég>
				<chlorures>13,5 mg</chlorures>
				<nitrates>6,3 mg</nitrates>
			</ions_nég>
			<autres>silice</autres>
		</contenu_par_litre>
	</Bouteille>
</BOUTEILLES>
