=== s0tiria/Document-structuring/exercices/exercice3b.dtd
<!ELEMENT tomes ((tome))>
<!ELEMENT tome EMPTY>
<!ATTLIST tome
	nb_pages CDATA #REQUIRED
>
<!ELEMENT titre EMPTY>
<!ATTLIST titre
	soustitre CDATA #IMPLIED
>
<!ELEMENT num EMPTY>
<!ELEMENT nb_pages EMPTY>
<!ELEMENT livres ((livre))>
<!ELEMENT livre ((titre, auteurs, tomes, edition))>
<!ELEMENT lieuImpression EMPTY>
<!ELEMENT lieuEdition EMPTY>
<!ELEMENT journal ((nb_pages, num))>
<!ATTLIST journal
    anneePub CDATA #DEFAULT inconnue
	nom CDATA #DEFAULT Feuille de Chou
>
<!ELEMENT edition ((editeur, lieuEdition, lieuImpression, ISBN))>
<!ELEMENT editeur EMPTY>
<!ELEMENT bibliographie ((livres, articles))>
<!ELEMENT auteurs ((auteur+))>
<!ELEMENT auteur EMPTY>
<!ELEMENT articles ((article))>
<!ELEMENT article ((titre, auteurs, journal))>
<!ELEMENT ISBN EMPTY>

=== s0tiria/Document-structuring/exercices/exercice3b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliographie SYSTEM "exercice3b.dtd">
<bibliographie>
	<livres>
		<livre>
			<titre soustitre=""/>
			<auteurs>
				<auteur/>
				<auteur/>
			</auteurs>
			<tomes>
				<tome nb_pages=""/>
			</tomes>
			<edition>
				<editeur/>
				<lieuEdition/>
				<lieuImpression/>
				<ISBN/>
			</edition>
		</livre>
	</livres>
	<articles>
		<article>
			<titre/>
			<auteurs>
				<auteur/>
			</auteurs>
			<journal nom="Feuille de Chou" anneePub="inconnue">
				<nb_pages/>
				<num/>
			</journal>
		</article>
	</articles>
</bibliographie>
